{{- if and .Values.keyVault .Values.keyVault.enabled (eq .Values.keyVault.enabled true) }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kvname-system-msi
spec:
  provider: azure
  secretObjects:
  - data:
      {{- include "helpers.secret-kv-data" . | nindent 4 }}

    secretName: {{ .Values.keyVault.secret | quote }}
    type: Opaque
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: ""
    keyvaultName: {{ .Values.keyVault.name | quote }}
    cloudName: ""
    objects: |
      array:
        {{- include "helpers.secret-kv-objects" . | nindent 6 }}
    tenantId: {{ .Values.keyVault.tenantId | quote }}
{{- end }}