apiVersion: v1
kind: Service
metadata:
  name: {{ include "metlife-chart.fullname" . }}
  labels:
    {{- include "metlife-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if and .Values.customService .Values.customService.enabled (eq .Values.customService.enabled true) }}
    - port: {{ .Values.customService.startupProbe.httpGet.port }}
      targetPort: customhttp
      protocol: TCP
      name: customhttp
    {{- end }}
  selector:
    {{- include "metlife-chart.selectorLabels" . | nindent 4 }}
